apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: transaction-api

  template:
    metadata:
      labels:
        app: transaction-api

    spec:
      containers:
      - name: transaction-api

        image: anildevopsr15/transaction-api:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"

        - name: DatabaseSettings__ConnectionString
          value: "mongodb://mongodb:27017"

        - name: EventBusSettings__HostAddress
          value: "amqp://guest:guest@rabbitmq:5672"

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-api-service

spec:
  selector:
    app: transaction-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
      - name: mongodb

        image: mongo:7

        imagePullPolicy: Always

        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb

spec:
  selector:
    app: mongodb

  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq

spec:
  replicas: 1

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:
      - name: rabbitmq

        image: rabbitmq:3-management

        imagePullPolicy: Always

        ports:
        - containerPort: 5672

        - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq

spec:
  selector:
    app: rabbitmq

  ports:
    - name: amqp
      port: 5672
      targetPort: 5672

    - name: management
      port: 15672
      targetPort: 15672

  type: ClusterIP
